---
env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/errors
  - prettier
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - import
  - prettier
rules:
  no-console: 0
  prefer-const: error
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-use-before-define': 'off'
settings:
  parser:
    '@typescript-eslint/parser':
      - '.js'
      - '.ts'
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.ts'
      paths:
        - src
